# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f52b33dfeb69e8b3176e07b84f4755f6dc022a18a9bea39d31abf2ac398147c763d4a6af59ded3126c6782348e716eca09f7f0f617d189b712d4fd3bcd176f0

test:
  secret_key_base: 8f103ed568d5be2c442df9f7d56c30e760de2caf5aeb597f58c729b7cd6254900a29ab22c45b7b82ea66486ba4ea3c1d093f121274d1e97e00e25a1e7f3ee529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
